server:
  port: 8081
  servlet:
    context-path: /booking/api/v1

spring:
  app:
    dev: kdb_dev


  datasource:
    url: jdbc:mysql://localhost:3306/bookingsystemdb
    username: root
    password: 2022

  jpa:

    hibernate:
      ddl-auto: update